# Copyright (c) Aakash Sethi
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: infineon_eval_foc

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyrproject-rtos-fork
      url-base: https://github.com/ASethi77

  projects:
    - name: zephyr
      remote: zephyrproject-rtos-fork
      revision: infineon_tle9879_ek_soc
      import: true
